### ISSUE TITLE
REST-API description / details of installation routine in HA

### ISSUE THREAD

**Issue by mweber5s** [RealDekkia/home-assistant-batterX-api#1]
Hi together, 

when adding the explained code to configuration.yaml no error occurs but the device is not recognized in HA. I expect the code for the rest-api must be also added to the configuration.yaml? But the code from the page linked is not correct; it's just the standard-code for the rest-api. Maybe you can explain a bit more in detail what must be modified here? 
Maybe you can give a more complete code for the configuration.yaml and your installation route?
Thank you in advance! 

Best regards, 
Marcus

**Comment by RealDekkia** [comment]
Hi,
The contents of configuration_example.yaml are the only things that need to be added to your configuration.yaml

This is a partial screenshot of my configuration:
![image](https://github.com/RealDekkia/home-assistant-batterX-api/assets/20802274/8848e601-6f97-4755-91d2-73b49d806e7c)

The links at the bottom of the readme are just a reference to where I got that information from.

This config also doesn't add a device because It wasn't needed for my use case. Instead, it just adds a bunch of entities:
![image](https://github.com/RealDekkia/home-assistant-batterX-api/assets/20802274/43bf1d62-6230-4696-b454-675504da05e2)

**Comment by mweber5s** [comment]
Thank you very much! 
It was actually my fault that the system didn't work... 
Just added the described content to the configuration.yaml, changed the IP of the system in your code and the entities were discovered.  
Best regards to Bavaria!
